"""Add day early end

Revision ID: 046d1f526fc6
Revises: eec1e4aa3ec5
Create Date: 2026-04-09 18:44:07.203267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '046d1f526fc6'
down_revision = 'eec1e4aa3ec5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_closed_on', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('day_closed_on')

    # ### end Alembic commands ###
