"""Update habit logs to include progress

Revision ID: 06bf0c097470
Revises: 9d439a5c8a82
Create Date: 2026-03-19 22:27:27.228820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06bf0c097470'
down_revision = '9d439a5c8a82'
branch_labels = None
depends_on = None


def upgrade():
    # 1. Add columns with a temporary default to avoid "NOT NULL constraint failed"
    with op.batch_alter_table('habit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress', sa.Integer(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('target_at_time', sa.Integer(), server_default='1', nullable=False))

    # --- DATA MIGRATION PHASE ---
    
    # 2. Backfill target_at_time with the habit's current target_count
    # (This safely assumes your past target is whatever your target is right now)
    op.execute("""
        UPDATE habit_logs
        SET target_at_time = (
            SELECT target_count 
            FROM habits 
            WHERE habits.id = habit_logs.habit_id
        )
    """)

    # 3. Consolidate Progress: Count all old duplicate rows and assign that number to 'progress'
    op.execute("""
        UPDATE habit_logs
        SET progress = (
            SELECT COUNT(*)
            FROM habit_logs hl2
            WHERE hl2.habit_id = habit_logs.habit_id
              AND hl2.completed_date = habit_logs.completed_date
        )
    """)

    # 4. Delete the duplicates! Keep only the first row (MIN id) for each habit/date combo
    op.execute("""
        DELETE FROM habit_logs
        WHERE id NOT IN (
            SELECT MIN(id)
            FROM habit_logs
            GROUP BY habit_id, completed_date
        )
    """)

    # --- SCHEMA LOCKDOWN PHASE ---

    # 5. NOW it is safe to apply the Unique Constraint because the duplicates are gone
    with op.batch_alter_table('habit_logs', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_habit_date', ['habit_id', 'completed_date'])
        
        # Optional: Remove the server_default now that the data is safely backfilled
        # (SQLite doesn't strictly require dropping it, but it's good practice)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habit_logs', schema=None) as batch_op:
        batch_op.drop_constraint('uq_habit_date', type_='unique')
        batch_op.drop_column('target_at_time')
        batch_op.drop_column('progress')

    # ### end Alembic commands ###
