"""Make theme and emotional value optional

Revision ID: 1d032751d1e6
Revises: a5205bb66a44
Create Date: 2026-02-26 20:59:12.742783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d032751d1e6'
down_revision = 'a5205bb66a44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.alter_column('theme_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('emotional_value_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.alter_column('emotional_value_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('theme_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
