"""Tie CoreThemes and EmotionalValue to user

Revision ID: 22bd8a71d849
Revises: 046d1f526fc6
Create Date: 2026-04-10 19:19:23.174993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22bd8a71d849'
down_revision = '046d1f526fc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core_themes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('core_themes_name_key', type_='unique')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('emotional_values', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('emotional_values_name_key', type_='unique')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emotional_values', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('emotional_values_name_key', ['name'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('core_themes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('core_themes_name_key', ['name'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
