"""Add timezone

Revision ID: 415385c6fa87
Revises: 2e182b7ee6df
Create Date: 2026-03-03 20:06:49.053592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '415385c6fa87'
down_revision = '2e182b7ee6df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.String(), server_default='UTC', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('timezone')

    # ### end Alembic commands ###
