"""Add ai notes to habits

Revision ID: 6fb75b4eb246
Revises: 22bd8a71d849
Create Date: 2026-05-01 23:01:13.101287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fb75b4eb246'
down_revision = '22bd8a71d849'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_insight', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_celebration', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.drop_column('ai_celebration')
        batch_op.drop_column('ai_insight')

    # ### end Alembic commands ###
