"""Update nullable attributes

Revision ID: 7a72ec71dcc6
Revises: d952ab91b0e2
Create Date: 2026-02-24 21:57:49.196008

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7a72ec71dcc6'
down_revision = 'd952ab91b0e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brain_dumps', schema=None) as batch_op:
        batch_op.alter_column('processed',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.alter_column('details',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('focus_sessions', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('end_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('total_paused_seconds',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('last_paused_tick',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.alter_column('identity',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('streak',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('last_completed',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('date_completed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('last_login',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('life_expectancy',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('life_expectancy',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('last_login',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('date_completed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.alter_column('last_completed',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('streak',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('identity',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('focus_sessions', schema=None) as batch_op:
        batch_op.alter_column('last_paused_tick',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('total_paused_seconds',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('end_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.alter_column('details',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('brain_dumps', schema=None) as batch_op:
        batch_op.alter_column('processed',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
