"""Add target count to habits

Revision ID: 8b83ffc9b189
Revises: bfdab00a9968
Create Date: 2026-03-16 18:00:34.811059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b83ffc9b189'
down_revision = 'bfdab00a9968'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_count', sa.Integer(), server_default='1', nullable=False))
        batch_op.alter_column('streak',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.alter_column('streak',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('target_count')

    # ### end Alembic commands ###
