"""Add AI notes

Revision ID: 93f2f0bbafed
Revises: d7351231e135
Create Date: 2026-04-06 22:11:41.992879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93f2f0bbafed'
down_revision = 'd7351231e135'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('logical_date', sa.Date(), nullable=False),
    sa.Column('ai_daily_briefing', sa.String(), nullable=True),
    sa.Column('ai_focus_empty_state', sa.String(), nullable=True),
    sa.Column('ai_habit_empty_state', sa.String(), nullable=True),
    sa.Column('ai_chapter_empty_state', sa.String(), nullable=True),
    sa.Column('ai_inbox_subtitle', sa.String(), nullable=True),
    sa.Column('ai_inbox_overload', sa.String(), nullable=True),
    sa.Column('ai_braindump_empty_state', sa.String(), nullable=True),
    sa.Column('ai_planner_subtitle', sa.String(), nullable=True),
    sa.Column('ai_planner_empty_state', sa.String(), nullable=True),
    sa.Column('ai_focus_analysis', sa.String(), nullable=True),
    sa.Column('ai_habits_subtitle', sa.String(), nullable=True),
    sa.Column('ai_habits_empty_state', sa.String(), nullable=True),
    sa.Column('ai_heatmap_analysis', sa.String(), nullable=True),
    sa.Column('ai_dow_analysis', sa.String(), nullable=True),
    sa.Column('ai_momentum_analysis', sa.String(), nullable=True),
    sa.Column('ai_identity_empty_state', sa.String(), nullable=True),
    sa.Column('ai_journals_subtitle', sa.String(), nullable=True),
    sa.Column('ai_journals_empty_state', sa.String(), nullable=True),
    sa.Column('ai_writing_coach', sa.String(), nullable=True),
    sa.Column('ai_prompt_suggestion', sa.String(), nullable=True),
    sa.Column('ai_archive_insight', sa.String(), nullable=True),
    sa.Column('ai_archive_empty_state', sa.String(), nullable=True),
    sa.Column('ai_map_subtitle', sa.String(), nullable=True),
    sa.Column('ai_lifemap_empty_state', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'logical_date', name='_user_logical_date_uc')
    )
    with op.batch_alter_table('brain_dumps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_insight', sa.String(), nullable=True))

    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_insight', sa.String(), nullable=True))

    with op.batch_alter_table('focus_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_intention', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('ai_insight', sa.String(), nullable=True))

    with op.batch_alter_table('habit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_celebration', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('ai_intervention', sa.String(), nullable=True))

    with op.batch_alter_table('identities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_insight', sa.String(), nullable=True))

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_insight', sa.String(), nullable=True))

    with op.batch_alter_table('journals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_insight', sa.String(), nullable=True))

    with op.batch_alter_table('time_buckets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_insight', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('ai_empty_state', sa.String(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_reset_hour', sa.Integer(), server_default='3', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('day_reset_hour')

    with op.batch_alter_table('time_buckets', schema=None) as batch_op:
        batch_op.drop_column('ai_empty_state')
        batch_op.drop_column('ai_insight')

    with op.batch_alter_table('journals', schema=None) as batch_op:
        batch_op.drop_column('ai_insight')

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_column('ai_insight')

    with op.batch_alter_table('identities', schema=None) as batch_op:
        batch_op.drop_column('ai_insight')

    with op.batch_alter_table('habit_logs', schema=None) as batch_op:
        batch_op.drop_column('ai_intervention')
        batch_op.drop_column('ai_celebration')

    with op.batch_alter_table('focus_sessions', schema=None) as batch_op:
        batch_op.drop_column('ai_insight')
        batch_op.drop_column('ai_intention')

    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_column('ai_insight')

    with op.batch_alter_table('brain_dumps', schema=None) as batch_op:
        batch_op.drop_column('ai_insight')

    op.drop_table('daily_notes')
    # ### end Alembic commands ###
