"""Add active attribute to habits

Revision ID: 9d439a5c8a82
Revises: 8b83ffc9b189
Create Date: 2026-03-19 21:31:18.617518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d439a5c8a82'
down_revision = '8b83ffc9b189'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    op.execute("UPDATE habits SET is_active = True WHERE is_active IS NULL")
    op.alter_column('habits', 'is_active', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
