"""Add identity

Revision ID: a092483a14d2
Revises: 8736c2320c53
Create Date: 2026-02-28 14:48:26.788798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a092483a14d2'
down_revision = '8736c2320c53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('focus_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identity_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'identities', ['identity_id'], ['id'])

    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identity_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'identities', ['identity_id'], ['id'])
        batch_op.drop_column('identity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identity', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('identity_id')

    with op.batch_alter_table('focus_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('identity_id')

    op.drop_table('identities')
    # ### end Alembic commands ###
