"""Replace LifeBuckets with TimeBuckets

Revision ID: a5205bb66a44
Revises: d0251d202c7d
Create Date: 2026-02-26 20:44:19.007743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5205bb66a44'
down_revision = 'd0251d202c7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_buckets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('theme', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bucket_experiences', schema=None) as batch_op:
        batch_op.drop_constraint('bucket_experiences_bucket_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'time_buckets', ['bucket_id'], ['id'])
    op.drop_table('life_buckets')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bucket_experiences', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('bucket_experiences_bucket_id_fkey', 'life_buckets', ['bucket_id'], ['id'])

    op.create_table('life_buckets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('theme', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='life_buckets_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='life_buckets_pkey')
    )
    op.drop_table('time_buckets')
    # ### end Alembic commands ###
