"""Handle on delete theme and emotional value in experience

Revision ID: a8776373240f
Revises: c1e2f6a18910
Create Date: 2026-02-26 22:17:13.637039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8776373240f'
down_revision = 'c1e2f6a18910'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_constraint('experiences_emotional_value_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('experiences_theme_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'emotional_values', ['emotional_value_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'core_themes', ['theme_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('experiences_theme_id_fkey', 'core_themes', ['theme_id'], ['id'])
        batch_op.create_foreign_key('experiences_emotional_value_id_fkey', 'emotional_values', ['emotional_value_id'], ['id'])

    # ### end Alembic commands ###
