"""Tie journal prompt to the entry

Revision ID: b472d983e6e7
Revises: f1a2b3c4d5e6
Create Date: 2026-03-22 22:06:54.960730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b472d983e6e7'
down_revision = 'f1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prompt_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'journal_prompts', ['prompt_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('prompt_id')

    # ### end Alembic commands ###
