"""Add additional fields to habits

Revision ID: bfdab00a9968
Revises: e2064bc70a9c
Create Date: 2026-03-16 16:52:13.377457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfdab00a9968'
down_revision = 'e2064bc70a9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('best_streak', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('trigger', sa.String(), nullable=True))

    op.execute("UPDATE habits SET best_streak = 0 WHERE best_streak IS NULL")
    op.alter_column('habits', 'best_streak', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.drop_column('trigger')
        batch_op.drop_column('description')
        batch_op.drop_column('best_streak')

    # ### end Alembic commands ###
