"""Add focus session duration

Revision ID: d0251d202c7d
Revises: 7a72ec71dcc6
Create Date: 2026-02-25 18:17:11.327393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0251d202c7d'
down_revision = '7a72ec71dcc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('focus_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_duration_minutes', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('focus_sessions', schema=None) as batch_op:
        batch_op.drop_column('target_duration_minutes')

    # ### end Alembic commands ###
