"""Time bucket theme nullable

Revision ID: d7351231e135
Revises: b472d983e6e7
Create Date: 2026-03-22 22:41:56.822396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7351231e135'
down_revision = 'b472d983e6e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_buckets', schema=None) as batch_op:
        batch_op.alter_column('theme',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_buckets', schema=None) as batch_op:
        batch_op.alter_column('theme',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
