"""Add color codes

Revision ID: e2064bc70a9c
Revises: 415385c6fa87
Create Date: 2026-03-10 16:05:08.974765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2064bc70a9c'
down_revision = '415385c6fa87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core_themes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=20), nullable=True))

    with op.batch_alter_table('emotional_values', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=20), nullable=True))

    with op.batch_alter_table('identities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=20), nullable=True))

    with op.batch_alter_table('journals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=20), nullable=True))

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_column('color')

    with op.batch_alter_table('journals', schema=None) as batch_op:
        batch_op.drop_column('color')

    with op.batch_alter_table('identities', schema=None) as batch_op:
        batch_op.drop_column('color')

    with op.batch_alter_table('emotional_values', schema=None) as batch_op:
        batch_op.drop_column('color')

    with op.batch_alter_table('core_themes', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
