"""Add habit created at attribute

Revision ID: e3bed0f30f6b
Revises: 06bf0c097470
Create Date: 2026-03-19 22:42:17.815245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3bed0f30f6b'
down_revision = '06bf0c097470'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
