"""Track user activity

Revision ID: eec1e4aa3ec5
Revises: 93f2f0bbafed
Create Date: 2026-04-08 21:55:07.007249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eec1e4aa3ec5'
down_revision = '93f2f0bbafed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_activities_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_activities_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_activities_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_activities_timestamp'))

    op.drop_table('user_activities')
    # ### end Alembic commands ###
